### ISSUE TITLE
Adding Employee breaks GUI

### ISSUE THREAD

**Issue by smeth194243** [Locke087/EmpData#4]
Admin permissions (I'm logged in as john doe)

Add an employee(I added one with admin permissions)

Upon save it does the thing where all the other employees go missing
![image](https://user-images.githubusercontent.com/21316661/206216917-bfc6da66-785a-4c88-af27-cc57ef666d5c.png)

According to the db file it saved the employee: 1234,Admin,Test,Executive,Making fat stacks,lovemytesla@gmail.com,1234 Address dr,,city,state,11111,country,111-111-1111,Salary,1111111111,11/11/2022,111-11-1111,12/12/2022,,11111111111,admin,wife,n,5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

These errors fire upon launching the program
PS C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData>
PS C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData> . 'c:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData\run.ps1'
cd : Cannot find path 'C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData\EmpData' because it     
does not exist.
At C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData\run.ps1:1 char:1
+ cd EmpData
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\School...EmpData\EmpData:String) [Set-Location], ItemNotFoundExcepti  
   on
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData\login.py", line 70, in login
    self.app = ViewEmployeeAdmin(self.master, employee)
  File "C:\Users\School\OneDrive - Utah Valley University\Desktop\Repositories\EmpData\view_employees.py", line 66, in __init__
    if employee.is_deactivated == 'n':
AttributeError: 'Employee' object has no attribute 'is_deactivated'

**Comment by smeth194243** [comment]
I tried adding an employee level employee and the same bug did NOT occur, that seems to work.

**Comment by smeth194243** [comment]
I just re-cloned and tried adding an admin again and it worked. Maybe you try testing it as well? It worries me that it's hit and miss.

**Comment by smeth194243** [comment]
Can't replicate anymore.
